### ISSUE TITLE
BUG: Possible JMPS=JMPW TMM Calculation Issue

### ISSUE THREAD

**Issue by TheDUZER** [itvbbjorn/itvbbjorn.github.io#6]
Example: Wolpertinger Jackalope shows TMM 4/3 with JMPW2, whereas Wulfen B shows TMM 4/2 and Osiris OSR-3D shows TMM 3/1 with JMPW2

**Comment by itvbbjorn** [comment]
The app doesn’t consider JMPW/JMPS when calculating TMM, it only calculates by MV. Will add a note to the rule tooltips in the next release or possibly recalculate if it has this special.

**Comment by itvbbjorn** [comment]
Added note to rule descriptions
